MySQL:
  host: localhost
  port: 3306
  user: root
  database: minecraft
  password: ''


Discord:
  token: CLIENTTOKEN
  game: Minecraft

Roles:
## If you are using BungeeCord you must give the user the permission "group.<groupname>"
## To get role ids just write  ad dm with "!roles" to your bot
  defaultrole: 7
  
Messages:
  verify: '&9&lDiscord &8>>&r Please send this message to our bot "!verify %code%"'
  #running: '&9&lDiscord &8>>&r There is already a verfication request in our system for you your code was %code%'
  verified: '&9&lDiscord &8>>&r You are already verified use /discord unlink to unlink your account'
  notverified: '&9&lDiscord &8>>&r You are not verified use /discord verify to verify your account'
  unlinked: '&9&lDiscord &8>>&r Successfully unlinked'
  #ts3join: 'Hey %user%, you are not verified yet if you want to be use /discord verify ingame'
  invalidcode: 'Your code was invalid!'
  success: 'Successfully linked ***IGN: %minecraft%*** with %discord%'
  updated: '&9&lDiscord &8>>&r Successfully updated discord ranks'
  help: 'Commands: %nl /discord verify %nl /discord unlink'
  reload: '&b&lDiscord reload configuration!'

